### PR TITLE
 server: use new stripe api version 

### PR DESCRIPTION
**Pull request by euank**
This updates us to `2018-02-06`.

These changes seem to work fine against the test API as best I can tell.

### CODE REVIEW

**Comment by euank** [comment]
@ilianaw deployed to staging [here](https://staging.pay.wobscale.website/) (using stripe test creds etc). If you want to click around and make sure nothing seems more broken than before, be my guest

**Comment by iliana** [comment]
+27,937 −3,150

help

**Comment by iliana** [comment]
Does this move us to the latest version of the Stripe REST API (i.e. the Stripe-Version header)?

**Comment by euank** [comment]
@ilianaw it moves us to `2018-02-06` in the Stripe-Version header

**Comment by euank** [comment]
@ilianaw Also pushed a commit to address the `newUser` issue you observed. I'm not sure that worked correctly before, but either way, fixed now.

**Review by iliana — APPROVED** [review]

**Pull request merged**
